
// This file has been generated by the GUI designer. Do not modify.
namespace Do.Platform.Linux
{
	public partial class PluginAvailableDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image title_img;
		private global::Gtk.Alignment title_align;
		private global::Gtk.Label title_lbl;
		private global::Gtk.Alignment body_align;
		private global::Gtk.Label body_lbl;
		private global::Gtk.Alignment link_align;
		private global::Gtk.VBox link_vbox;
		private global::Gtk.Alignment ask_align;
		private global::Gtk.CheckButton ask_chk;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button install_btn;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Do.Platform.Linux.PluginAvailableDialog
			this.Name = "Do.Platform.Linux.PluginAvailableDialog";
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "distributor-logo", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(5));
			// Internal child Do.Platform.Linux.PluginAvailableDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.title_img = new global::Gtk.Image ();
			this.title_img.Name = "title_img";
			this.title_img.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gnome-do", global::Gtk.IconSize.Dialog);
			this.hbox1.Add (this.title_img);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.title_img]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.title_align = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.title_align.Name = "title_align";
			this.title_align.LeftPadding = ((uint)(7));
			// Container child title_align.Gtk.Container+ContainerChild
			this.title_lbl = new global::Gtk.Label ();
			this.title_lbl.Name = "title_lbl";
			this.title_lbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><span size=\"x-large\">There's a Do plugin for that!</span></b>");
			this.title_lbl.UseMarkup = true;
			this.title_align.Add (this.title_lbl);
			this.hbox1.Add (this.title_align);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.title_align]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.body_align = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.body_align.Name = "body_align";
			this.body_align.LeftPadding = ((uint)(62));
			// Container child body_align.Gtk.Container+ContainerChild
			this.body_lbl = new global::Gtk.Label ();
			this.body_lbl.Name = "body_lbl";
			this.body_lbl.Xalign = 0F;
			this.body_lbl.LabelProp = global::Mono.Unix.Catalog.GetString ("A Do plugin for {0} is available for installation. Would you like us to enable it for you?");
			this.body_lbl.Wrap = true;
			this.body_align.Add (this.body_lbl);
			this.vbox2.Add (this.body_align);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.body_align]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.link_align = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.link_align.Name = "link_align";
			this.link_align.LeftPadding = ((uint)(55));
			// Container child link_align.Gtk.Container+ContainerChild
			this.link_vbox = new global::Gtk.VBox ();
			this.link_vbox.Name = "link_vbox";
			this.link_align.Add (this.link_vbox);
			this.vbox2.Add (this.link_align);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.link_align]));
			w9.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.ask_align = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.ask_align.Name = "ask_align";
			this.ask_align.LeftPadding = ((uint)(57));
			// Container child ask_align.Gtk.Container+ContainerChild
			this.ask_chk = new global::Gtk.CheckButton ();
			this.ask_chk.CanFocus = true;
			this.ask_chk.Name = "ask_chk";
			this.ask_chk.Label = global::Mono.Unix.Catalog.GetString ("Don't ask me about Do plugins again.");
			this.ask_chk.DrawIndicator = true;
			this.ask_chk.UseUnderline = true;
			this.ask_align.Add (this.ask_chk);
			this.vbox2.Add (this.ask_align);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ask_align]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w12.Position = 0;
			// Internal child Do.Platform.Linux.PluginAvailableDialog.ActionArea
			global::Gtk.HButtonBox w13 = this.ActionArea;
			w13.Name = "dialog1_ActionArea";
			w13.Spacing = 6;
			w13.BorderWidth = ((uint)(5));
			w13.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonCancel]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.install_btn = new global::Gtk.Button ();
			this.install_btn.CanDefault = true;
			this.install_btn.CanFocus = true;
			this.install_btn.Name = "install_btn";
			this.install_btn.UseUnderline = true;
			this.install_btn.Label = global::Mono.Unix.Catalog.GetString ("_Install");
			global::Gtk.Image w15 = new global::Gtk.Image ();
			w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Button);
			this.install_btn.Image = w15;
			this.AddActionWidget (this.install_btn, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.install_btn]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 486;
			this.DefaultHeight = 218;
			this.Show ();
			this.ask_chk.Toggled += new global::System.EventHandler (this.OnAskChkToggled);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.install_btn.Clicked += new global::System.EventHandler (this.OnInstallBtnClicked);
		}
	}
}
