// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.UI {
    
    
    public partial class ColorConfigurationWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Alignment alignment2;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label theme_lbl;
        
        private Gtk.ComboBox theme_combo;
        
        private Gtk.VBox vbox3;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.CheckButton pin_check;
        
        private Gtk.Alignment theme_configuration_container;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.VBox composite_warning_widget;
        
        private Gtk.Label label1;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button composite_warning_info_btn;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.UI.ColorConfigurationWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Do.UI.ColorConfigurationWidget";
            // Container child Do.UI.ColorConfigurationWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(5));
            this.GtkAlignment.TopPadding = ((uint)(5));
            this.GtkAlignment.RightPadding = ((uint)(5));
            this.GtkAlignment.BottomPadding = ((uint)(10));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.alignment2 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment2.Name = "alignment2";
            // Container child alignment2.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.theme_lbl = new Gtk.Label();
            this.theme_lbl.Name = "theme_lbl";
            this.theme_lbl.Xalign = 0F;
            this.theme_lbl.LabelProp = Mono.Unix.Catalog.GetString("_Theme:");
            this.theme_lbl.UseUnderline = true;
            this.hbox4.Add(this.theme_lbl);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox4[this.theme_lbl]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.theme_combo = Gtk.ComboBox.NewText();
            this.theme_combo.Name = "theme_combo";
            this.hbox4.Add(this.theme_combo);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox4[this.theme_combo]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.vbox1.Add(this.hbox4);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Homogeneous = true;
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.pin_check = new Gtk.CheckButton();
            this.pin_check.CanFocus = true;
            this.pin_check.Name = "pin_check";
            this.pin_check.Label = Mono.Unix.Catalog.GetString("Always show results window");
            this.pin_check.Active = true;
            this.pin_check.DrawIndicator = true;
            this.pin_check.UseUnderline = true;
            this.hbox2.Add(this.pin_check);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.pin_check]));
            w4.Position = 0;
            this.vbox4.Add(this.hbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox3.Add(this.vbox4);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            this.vbox1.Add(this.vbox3);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.alignment2.Add(this.vbox1);
            this.GtkAlignment.Add(this.alignment2);
            this.frame1.Add(this.GtkAlignment);
            this.vbox2.Add(this.frame1);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.theme_configuration_container = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.theme_configuration_container.Name = "theme_configuration_container";
            this.theme_configuration_container.LeftPadding = ((uint)(6));
            this.theme_configuration_container.RightPadding = ((uint)(6));
            this.theme_configuration_container.BottomPadding = ((uint)(3));
            this.vbox2.Add(this.theme_configuration_container);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox2[this.theme_configuration_container]));
            w12.PackType = ((Gtk.PackType)(1));
            w12.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox2.Add(this.hseparator1);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
            w13.PackType = ((Gtk.PackType)(1));
            w13.Position = 2;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.composite_warning_widget = new Gtk.VBox();
            this.composite_warning_widget.Name = "composite_warning_widget";
            this.composite_warning_widget.Spacing = 6;
            // Container child composite_warning_widget.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<b>Your display is not properly configured for theme and animation support. To use these features, you must enable compositing.</b>");
            this.label1.UseMarkup = true;
            this.label1.Wrap = true;
            this.composite_warning_widget.Add(this.label1);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.composite_warning_widget[this.label1]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child composite_warning_widget.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.composite_warning_info_btn = new Gtk.Button();
            this.composite_warning_info_btn.CanFocus = true;
            this.composite_warning_info_btn.Name = "composite_warning_info_btn";
            this.composite_warning_info_btn.UseStock = true;
            this.composite_warning_info_btn.UseUnderline = true;
            this.composite_warning_info_btn.Label = "gtk-dialog-info";
            this.hbuttonbox1.Add(this.composite_warning_info_btn);
            Gtk.ButtonBox.ButtonBoxChild w15 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.composite_warning_info_btn]));
            w15.Expand = false;
            w15.Fill = false;
            this.composite_warning_widget.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.composite_warning_widget[this.hbuttonbox1]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            this.vbox2.Add(this.composite_warning_widget);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox2[this.composite_warning_widget]));
            w17.PackType = ((Gtk.PackType)(1));
            w17.Position = 3;
            w17.Expand = false;
            w17.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.composite_warning_info_btn.Hide();
            this.composite_warning_widget.Hide();
            this.Show();
            this.theme_combo.Changed += new System.EventHandler(this.OnThemeComboChanged);
            this.pin_check.Clicked += new System.EventHandler(this.OnPinCheckClicked);
            this.composite_warning_info_btn.Clicked += new System.EventHandler(this.OnCompositeWarningInfoBtnClicked);
        }
    }
}
