// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.UI {
    
    
    public partial class SettingsWindow {
        
        private Gtk.RadioAction ManagePluginsAction;
        
        private Gtk.RadioAction GeneralPreferencesAction;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Toolbar toolbar1;
        
        private Gtk.Notebook mainNotebook;
        
        private Gtk.HPaned hpaned2;
        
        private Gtk.ScrolledWindow nodeScroll;
        
        private Gtk.Fixed fixed2;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label name_label;
        
        private Gtk.Label author_label;
        
        private Gtk.Label description_label;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Label manage_plugins_lbl;
        
        private Gtk.Label label1;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Button ok_btn;
        
        private Gtk.Button help_btn;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.UI.SettingsWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.ManagePluginsAction = new Gtk.RadioAction("ManagePluginsAction", Mono.Unix.Catalog.GetString("_Manage Plugins"), null, "gtk-execute", 0);
            this.ManagePluginsAction.Group = new GLib.SList(System.IntPtr.Zero);
            this.ManagePluginsAction.ShortLabel = Mono.Unix.Catalog.GetString("_Manage Plugins");
            w2.Add(this.ManagePluginsAction, null);
            this.GeneralPreferencesAction = new Gtk.RadioAction("GeneralPreferencesAction", Mono.Unix.Catalog.GetString("General _Preferences"), null, "gtk-preferences", 0);
            this.GeneralPreferencesAction.Group = this.ManagePluginsAction.Group;
            this.GeneralPreferencesAction.ShortLabel = Mono.Unix.Catalog.GetString("General _Preferences");
            w2.Add(this.GeneralPreferencesAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "Do.UI.SettingsWindow";
            this.Title = Mono.Unix.Catalog.GetString("Do Settings");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-preferences", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.DefaultWidth = 600;
            this.DefaultHeight = 350;
            // Container child Do.UI.SettingsWindow.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='GeneralPreferencesAction'/><toolitem action='ManagePluginsAction'/></toolbar></ui>");
            this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
            this.toolbar1.Name = "toolbar1";
            this.toolbar1.ShowArrow = false;
            this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(2));
            this.toolbar1.IconSize = ((Gtk.IconSize)(5));
            this.vbox3.Add(this.toolbar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.toolbar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.mainNotebook = new Gtk.Notebook();
            this.mainNotebook.CanFocus = true;
            this.mainNotebook.Name = "mainNotebook";
            this.mainNotebook.CurrentPage = 0;
            this.mainNotebook.ShowBorder = false;
            this.mainNotebook.ShowTabs = false;
            // Container child mainNotebook.Gtk.Notebook+NotebookChild
            this.hpaned2 = new Gtk.HPaned();
            this.hpaned2.CanFocus = true;
            this.hpaned2.Name = "hpaned2";
            this.hpaned2.Position = 201;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.nodeScroll = new Gtk.ScrolledWindow();
            this.nodeScroll.CanFocus = true;
            this.nodeScroll.Name = "nodeScroll";
            this.nodeScroll.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.nodeScroll.ShadowType = ((Gtk.ShadowType)(1));
            this.hpaned2.Add(this.nodeScroll);
            Gtk.Paned.PanedChild w4 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.nodeScroll]));
            w4.Resize = false;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.fixed2 = new Gtk.Fixed();
            this.fixed2.Name = "fixed2";
            this.fixed2.HasWindow = false;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.fixed2.Add(this.label2);
            Gtk.Fixed.FixedChild w5 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.label2]));
            w5.X = 10;
            w5.Y = 15;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Description:");
            this.fixed2.Add(this.label3);
            Gtk.Fixed.FixedChild w6 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
            w6.X = 10;
            w6.Y = 120;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Author: ");
            this.fixed2.Add(this.label4);
            Gtk.Fixed.FixedChild w7 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.label4]));
            w7.X = 10;
            w7.Y = 50;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.name_label = new Gtk.Label();
            this.name_label.Name = "name_label";
            this.name_label.LabelProp = "";
            this.fixed2.Add(this.name_label);
            Gtk.Fixed.FixedChild w8 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.name_label]));
            w8.X = 110;
            w8.Y = 15;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.author_label = new Gtk.Label();
            this.author_label.Name = "author_label";
            this.author_label.LabelProp = "";
            this.fixed2.Add(this.author_label);
            Gtk.Fixed.FixedChild w9 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.author_label]));
            w9.X = 110;
            w9.Y = 50;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.description_label = new Gtk.Label();
            this.description_label.Name = "description_label";
            this.description_label.LabelProp = "";
            this.fixed2.Add(this.description_label);
            Gtk.Fixed.FixedChild w10 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.description_label]));
            w10.X = 110;
            w10.Y = 120;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Version:");
            this.fixed2.Add(this.label7);
            Gtk.Fixed.FixedChild w11 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.label7]));
            w11.X = 10;
            w11.Y = 85;
            // Container child fixed2.Gtk.Fixed+FixedChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = "";
            this.fixed2.Add(this.label8);
            Gtk.Fixed.FixedChild w12 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.label8]));
            w12.X = 110;
            w12.Y = 85;
            this.hpaned2.Add(this.fixed2);
            this.mainNotebook.Add(this.hpaned2);
            // Notebook tab
            this.manage_plugins_lbl = new Gtk.Label();
            this.manage_plugins_lbl.Name = "manage_plugins_lbl";
            this.manage_plugins_lbl.LabelProp = Mono.Unix.Catalog.GetString("Manage Plugins");
            this.mainNotebook.SetTabLabel(this.hpaned2, this.manage_plugins_lbl);
            this.manage_plugins_lbl.ShowAll();
            // Notebook tab
            Gtk.Label w15 = new Gtk.Label();
            w15.Visible = true;
            this.mainNotebook.Add(w15);
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("General Preferences");
            this.mainNotebook.SetTabLabel(w15, this.label1);
            this.label1.ShowAll();
            this.vbox3.Add(this.mainNotebook);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox3[this.mainNotebook]));
            w16.Position = 1;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox3.Add(this.hseparator1);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
            w17.Position = 2;
            w17.Expand = false;
            w17.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.HeightRequest = 35;
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.ok_btn = new Gtk.Button();
            this.ok_btn.WidthRequest = 80;
            this.ok_btn.HeightRequest = 30;
            this.ok_btn.CanDefault = true;
            this.ok_btn.CanFocus = true;
            this.ok_btn.Name = "ok_btn";
            this.ok_btn.UseUnderline = true;
            // Container child ok_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w18 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w19 = new Gtk.HBox();
            w19.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w20 = new Gtk.Image();
            w20.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-ok", Gtk.IconSize.Menu, 16);
            w19.Add(w20);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w22 = new Gtk.Label();
            w22.LabelProp = Mono.Unix.Catalog.GetString("Ok");
            w22.UseUnderline = true;
            w19.Add(w22);
            w18.Add(w19);
            this.ok_btn.Add(w18);
            this.fixed1.Add(this.ok_btn);
            Gtk.Fixed.FixedChild w26 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.ok_btn]));
            w26.X = 564;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.help_btn = new Gtk.Button();
            this.help_btn.WidthRequest = 80;
            this.help_btn.HeightRequest = 30;
            this.help_btn.CanFocus = true;
            this.help_btn.Name = "help_btn";
            this.help_btn.UseUnderline = true;
            // Container child help_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w27 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w28 = new Gtk.HBox();
            w28.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w29 = new Gtk.Image();
            w29.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-help", Gtk.IconSize.Menu, 16);
            w28.Add(w29);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w31 = new Gtk.Label();
            w31.LabelProp = Mono.Unix.Catalog.GetString("Help");
            w31.UseUnderline = true;
            w28.Add(w31);
            w27.Add(w28);
            this.help_btn.Add(w27);
            this.fixed1.Add(this.help_btn);
            Gtk.Fixed.FixedChild w35 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.help_btn]));
            w35.X = 5;
            this.vbox3.Add(this.fixed1);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox3[this.fixed1]));
            w36.Position = 3;
            w36.Expand = false;
            w36.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.ok_btn.HasDefault = true;
            this.Show();
            this.ManagePluginsAction.Activated += new System.EventHandler(this.plugins_btnClicked);
            this.GeneralPreferencesAction.Activated += new System.EventHandler(this.preferences_btnClicked);
            this.ok_btn.Clicked += new System.EventHandler(this.ok_btnClicked);
            this.help_btn.Clicked += new System.EventHandler(this.help_btnClicked);
        }
    }
}
