// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.UI {
    
    
    public partial class ManagePluginsPreferencesWidget {
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Button btn_manage_plugins;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.UI.ManagePluginsPreferencesWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Do.UI.ManagePluginsPreferencesWidget";
            // Container child Do.UI.ManagePluginsPreferencesWidget.Gtk.Container+ContainerChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.btn_manage_plugins = new Gtk.Button();
            this.btn_manage_plugins.CanFocus = true;
            this.btn_manage_plugins.Name = "btn_manage_plugins";
            this.btn_manage_plugins.UseUnderline = true;
            // Container child btn_manage_plugins.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-execute", Gtk.IconSize.Button, 20);
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w5.LabelProp = Mono.Unix.Catalog.GetString("Manage plugins...");
            w5.UseUnderline = true;
            w2.Add(w5);
            w1.Add(w2);
            this.btn_manage_plugins.Add(w1);
            this.fixed1.Add(this.btn_manage_plugins);
            Gtk.Fixed.FixedChild w9 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.btn_manage_plugins]));
            w9.X = 81;
            w9.Y = 56;
            this.Add(this.fixed1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.btn_manage_plugins.Clicked += new System.EventHandler(this.OnBtnManagePluginsClicked);
        }
    }
}
