
// This file has been generated by the GUI designer. Do not modify.
namespace Do.UI
{
	public partial class DoAddinInstallerDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label addinList;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.ScrolledWindow plugin_scroll;
		private global::Gtk.ProgressBar progress_bar;
		private global::Gtk.Button button_cancel;
		private global::Gtk.Button button_ok;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Do.UI.DoAddinInstallerDialog
			this.Name = "Do.UI.DoAddinInstallerDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Do.UI.DoAddinInstallerDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.addinList = new global::Gtk.Label ();
			this.addinList.Name = "addinList";
			this.addinList.Xpad = 5;
			this.addinList.Ypad = 3;
			this.addinList.Xalign = 0F;
			this.addinList.Yalign = 0F;
			this.addinList.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"large\"><b>Updated plugins are available!</b></span>");
			this.addinList.UseMarkup = true;
			this.vbox2.Add (this.addinList);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.addinList]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(12));
			this.alignment1.TopPadding = ((uint)(12));
			this.alignment1.RightPadding = ((uint)(12));
			this.alignment1.BottomPadding = ((uint)(24));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.plugin_scroll = new global::Gtk.ScrolledWindow ();
			this.plugin_scroll.CanFocus = true;
			this.plugin_scroll.Name = "plugin_scroll";
			this.plugin_scroll.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox3.Add (this.plugin_scroll);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.plugin_scroll]));
			w3.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.progress_bar = new global::Gtk.ProgressBar ();
			this.progress_bar.Name = "progress_bar";
			this.progress_bar.Ellipsize = ((global::Pango.EllipsizeMode)(2));
			this.vbox3.Add (this.progress_bar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.progress_bar]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.alignment1.Add (this.vbox3);
			this.vbox2.Add (this.alignment1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment1]));
			w6.Position = 1;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w7.Position = 0;
			// Internal child Do.UI.DoAddinInstallerDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 6;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button_cancel = new global::Gtk.Button ();
			this.button_cancel.CanFocus = true;
			this.button_cancel.Name = "button_cancel";
			this.button_cancel.UseStock = true;
			this.button_cancel.UseUnderline = true;
			this.button_cancel.Label = "gtk-cancel";
			this.AddActionWidget (this.button_cancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.button_cancel]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button_ok = new global::Gtk.Button ();
			this.button_ok.CanDefault = true;
			this.button_ok.CanFocus = true;
			this.button_ok.Name = "button_ok";
			this.button_ok.UseUnderline = true;
			this.button_ok.Label = global::Mono.Unix.Catalog.GetString ("_Install Updates");
			global::Gtk.Image w10 = new global::Gtk.Image ();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Button);
			this.button_ok.Image = w10;
			this.AddActionWidget (this.button_ok, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.button_ok]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 443;
			this.DefaultHeight = 463;
			this.progress_bar.Hide ();
			this.Show ();
			this.button_ok.Clicked += new global::System.EventHandler (this.OnButtonOKClick);
		}
	}
}
