// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.UI {
    
    
    public partial class ColorConfigurationWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Table table2;
        
        private Gtk.ComboBox background_combo;
        
        private Gtk.Button clear_radius;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.ComboBox outline_combo;
        
        private Gtk.SpinButton radius_spin;
        
        private Gtk.ComboBox title_combo;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label8;
        
        private Gtk.ColorButton background_colorbutton;
        
        private Gtk.Button clear_background;
        
        private Gtk.CheckButton shadow_check;
        
        private Gtk.Frame preview_frame;
        
        private Gtk.Alignment preview_align;
        
        private Gtk.Label GtkLabel3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.UI.ColorConfigurationWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Do.UI.ColorConfigurationWidget";
            // Container child Do.UI.ColorConfigurationWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(3)), ((uint)(7)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            this.table2.BorderWidth = ((uint)(15));
            // Container child table2.Gtk.Table+TableChild
            this.background_combo = Gtk.ComboBox.NewText();
            this.background_combo.AppendText(Mono.Unix.Catalog.GetString("Default"));
            this.background_combo.AppendText(Mono.Unix.Catalog.GetString("HUD"));
            this.background_combo.AppendText(Mono.Unix.Catalog.GetString("Classic"));
            this.background_combo.Name = "background_combo";
            this.background_combo.Active = 0;
            this.table2.Add(this.background_combo);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table2[this.background_combo]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(2));
            w1.RightAttach = ((uint)(3));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.clear_radius = new Gtk.Button();
            this.clear_radius.CanFocus = true;
            this.clear_radius.Name = "clear_radius";
            this.clear_radius.UseStock = true;
            this.clear_radius.UseUnderline = true;
            this.clear_radius.Label = "gtk-clear";
            this.table2.Add(this.clear_radius);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.clear_radius]));
            w2.LeftAttach = ((uint)(6));
            w2.RightAttach = ((uint)(7));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Title Bar Style:");
            this.table2.Add(this.label4);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.label4]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Background Style:");
            this.table2.Add(this.label5);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.label5]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Outline Style:");
            this.table2.Add(this.label6);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.label6]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Rounding Radius:");
            this.table2.Add(this.label7);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.label7]));
            w6.LeftAttach = ((uint)(4));
            w6.RightAttach = ((uint)(5));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.outline_combo = Gtk.ComboBox.NewText();
            this.outline_combo.AppendText(Mono.Unix.Catalog.GetString("Default"));
            this.outline_combo.AppendText(Mono.Unix.Catalog.GetString("HUD"));
            this.outline_combo.AppendText(Mono.Unix.Catalog.GetString("Classic"));
            this.outline_combo.Name = "outline_combo";
            this.outline_combo.Active = 0;
            this.table2.Add(this.outline_combo);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table2[this.outline_combo]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.LeftAttach = ((uint)(2));
            w7.RightAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.radius_spin = new Gtk.SpinButton(0, 25, 1);
            this.radius_spin.CanFocus = true;
            this.radius_spin.Name = "radius_spin";
            this.radius_spin.Adjustment.PageIncrement = 10;
            this.radius_spin.ClimbRate = 1;
            this.radius_spin.Numeric = true;
            this.radius_spin.Value = 6;
            this.table2.Add(this.radius_spin);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table2[this.radius_spin]));
            w8.LeftAttach = ((uint)(5));
            w8.RightAttach = ((uint)(6));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.title_combo = Gtk.ComboBox.NewText();
            this.title_combo.AppendText(Mono.Unix.Catalog.GetString("Default"));
            this.title_combo.AppendText(Mono.Unix.Catalog.GetString("HUD"));
            this.title_combo.AppendText(Mono.Unix.Catalog.GetString("Classic"));
            this.title_combo.Name = "title_combo";
            this.title_combo.Active = 0;
            this.table2.Add(this.title_combo);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.title_combo]));
            w9.LeftAttach = ((uint)(2));
            w9.RightAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.table2]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 0F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Background Color:");
            this.hbox1.Add(this.label8);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.label8]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.background_colorbutton = new Gtk.ColorButton();
            this.background_colorbutton.CanFocus = true;
            this.background_colorbutton.Events = ((Gdk.EventMask)(784));
            this.background_colorbutton.Name = "background_colorbutton";
            this.hbox1.Add(this.background_colorbutton);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.background_colorbutton]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.clear_background = new Gtk.Button();
            this.clear_background.CanFocus = true;
            this.clear_background.Name = "clear_background";
            this.clear_background.UseStock = true;
            this.clear_background.UseUnderline = true;
            this.clear_background.Relief = ((Gtk.ReliefStyle)(2));
            this.clear_background.Label = "gtk-clear";
            this.hbox1.Add(this.clear_background);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox1[this.clear_background]));
            w13.Position = 2;
            w13.Expand = false;
            w13.Fill = false;
            this.alignment1.Add(this.hbox1);
            this.vbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.shadow_check = new Gtk.CheckButton();
            this.shadow_check.CanFocus = true;
            this.shadow_check.Name = "shadow_check";
            this.shadow_check.Label = Mono.Unix.Catalog.GetString("Draw Shadow");
            this.shadow_check.DrawIndicator = true;
            this.shadow_check.UseUnderline = true;
            this.vbox2.Add(this.shadow_check);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox2[this.shadow_check]));
            w16.Position = 2;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.preview_frame = new Gtk.Frame();
            this.preview_frame.Name = "preview_frame";
            // Container child preview_frame.Gtk.Container+ContainerChild
            this.preview_align = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.preview_align.Name = "preview_align";
            this.preview_align.LeftPadding = ((uint)(12));
            this.preview_align.RightPadding = ((uint)(12));
            this.preview_align.BottomPadding = ((uint)(6));
            this.preview_frame.Add(this.preview_align);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Preview</b>");
            this.GtkLabel3.UseMarkup = true;
            this.preview_frame.LabelWidget = this.GtkLabel3;
            this.vbox2.Add(this.preview_frame);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox2[this.preview_frame]));
            w18.Position = 3;
            w18.Expand = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.background_colorbutton.ColorSet += new System.EventHandler(this.OnBackgroundColorbuttonColorSet);
            this.clear_background.Clicked += new System.EventHandler(this.OnClearBackgroundClicked);
            this.shadow_check.Clicked += new System.EventHandler(this.OnShadowCheckClicked);
        }
    }
}
