
// This file has been generated by the GUI designer. Do not modify.
namespace Do.UI
{
	public partial class KeybindingsPreferencesWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.ScrolledWindow action_scroll;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image help_icn;
		private global::Gtk.Label help_lbl;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Do.UI.KeybindingsPreferencesWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Do.UI.KeybindingsPreferencesWidget";
			// Container child Do.UI.KeybindingsPreferencesWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.action_scroll = new global::Gtk.ScrolledWindow ();
			this.action_scroll.CanFocus = true;
			this.action_scroll.Name = "action_scroll";
			this.action_scroll.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox2.Add (this.action_scroll);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.action_scroll]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.help_icn = new global::Gtk.Image ();
			this.help_icn.Name = "help_icn";
			this.help_icn.Yalign = 0F;
			this.help_icn.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Dnd);
			this.hbox1.Add (this.help_icn);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.help_icn]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.help_lbl = new global::Gtk.Label ();
			this.help_lbl.Name = "help_lbl";
			this.help_lbl.Ypad = 1;
			this.help_lbl.Xalign = 0F;
			this.help_lbl.LabelProp = global::Mono.Unix.Catalog.GetString ("To edit a shortcut, double-click it and type a new one.\nTo restore a shortcut to the default, double click and press Backspace.");
			this.help_lbl.Wrap = true;
			this.hbox1.Add (this.help_lbl);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.help_lbl]));
			w3.Position = 1;
			w3.Padding = ((uint)(10));
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
