// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.UI {
    
    
    public partial class DoAddinInstallerDialog {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label addinList;
        
        private Gtk.ScrolledWindow plugin_scroll;
        
        private Gtk.ProgressBar progressBar;
        
        private Gtk.Button button_cancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.UI.DoAddinInstallerDialog
            this.Name = "Do.UI.DoAddinInstallerDialog";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Do.UI.DoAddinInstallerDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.addinList = new Gtk.Label();
            this.addinList.Name = "addinList";
            this.addinList.Xpad = 5;
            this.addinList.Ypad = 3;
            this.addinList.Xalign = 0F;
            this.addinList.Yalign = 0F;
            this.addinList.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"large\"><b>Updated plugins are available!</b></span>");
            this.addinList.UseMarkup = true;
            this.vbox2.Add(this.addinList);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.addinList]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.plugin_scroll = new Gtk.ScrolledWindow();
            this.plugin_scroll.CanFocus = true;
            this.plugin_scroll.Name = "plugin_scroll";
            this.plugin_scroll.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox2.Add(this.plugin_scroll);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.plugin_scroll]));
            w3.Position = 1;
            w3.Padding = ((uint)(8));
            // Container child vbox2.Gtk.Box+BoxChild
            this.progressBar = new Gtk.ProgressBar();
            this.progressBar.Name = "progressBar";
            this.vbox2.Add(this.progressBar);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.progressBar]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            w4.Padding = ((uint)(5));
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w5.Position = 0;
            // Internal child Do.UI.DoAddinInstallerDialog.ActionArea
            Gtk.HButtonBox w6 = this.ActionArea;
            w6.Name = "dialog1_ActionArea";
            w6.Spacing = 6;
            w6.BorderWidth = ((uint)(5));
            w6.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button_cancel = new Gtk.Button();
            this.button_cancel.CanFocus = true;
            this.button_cancel.Name = "button_cancel";
            this.button_cancel.UseStock = true;
            this.button_cancel.UseUnderline = true;
            this.button_cancel.Label = "gtk-cancel";
            this.AddActionWidget(this.button_cancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(w6[this.button_cancel]));
            w7.Expand = false;
            w7.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseUnderline = true;
            // Container child buttonOk.Gtk.Container+ContainerChild
            Gtk.Alignment w8 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            Gtk.HBox w9 = new Gtk.HBox();
            w9.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w10 = new Gtk.Image();
            w10.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-ok", Gtk.IconSize.Button, 20);
            w9.Add(w10);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w12 = new Gtk.Label();
            w12.LabelProp = Mono.Unix.Catalog.GetString("_Install Updates");
            w12.UseUnderline = true;
            w9.Add(w12);
            w8.Add(w9);
            this.buttonOk.Add(w8);
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w16 = ((Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonOk]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 443;
            this.DefaultHeight = 463;
            this.Show();
            this.buttonOk.Clicked += new System.EventHandler(this.OnButtonOKClick);
        }
    }
}
