// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.UI {
    
    
    public partial class PreferencesWindow {
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow scroll_window;
        
        private Gtk.Notebook notebook;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Button btn_close;
        
        private Gtk.Button btn_help;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.UI.PreferencesWindow
            this.WidthRequest = 580;
            this.HeightRequest = 500;
            this.Name = "Do.UI.PreferencesWindow";
            this.Title = Mono.Unix.Catalog.GetString("Preferences");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-preferences", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.BorderWidth = ((uint)(6));
            this.Resizable = false;
            this.AllowGrow = false;
            // Container child Do.UI.PreferencesWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.HeightRequest = 440;
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.scroll_window = new Gtk.ScrolledWindow();
            this.scroll_window.CanFocus = true;
            this.scroll_window.Name = "scroll_window";
            this.scroll_window.ShadowType = ((Gtk.ShadowType)(1));
            this.hbox1.Add(this.scroll_window);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.scroll_window]));
            w1.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.notebook = new Gtk.Notebook();
            this.notebook.WidthRequest = 300;
            this.notebook.CanFocus = true;
            this.notebook.Name = "notebook";
            this.notebook.CurrentPage = 0;
            this.notebook.ShowTabs = false;
            this.hbox1.Add(this.notebook);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.notebook]));
            w2.Position = 1;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w3.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox1.Add(this.hseparator1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.HeightRequest = 36;
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.btn_close = new Gtk.Button();
            this.btn_close.WidthRequest = 80;
            this.btn_close.CanDefault = true;
            this.btn_close.CanFocus = true;
            this.btn_close.Name = "btn_close";
            this.btn_close.UseStock = true;
            this.btn_close.UseUnderline = true;
            this.btn_close.Label = "gtk-close";
            this.fixed1.Add(this.btn_close);
            Gtk.Fixed.FixedChild w5 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.btn_close]));
            w5.X = 488;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.btn_help = new Gtk.Button();
            this.btn_help.WidthRequest = 80;
            this.btn_help.CanFocus = true;
            this.btn_help.Name = "btn_help";
            this.btn_help.UseStock = true;
            this.btn_help.UseUnderline = true;
            this.btn_help.Label = "gtk-help";
            this.fixed1.Add(this.btn_help);
            this.vbox1.Add(this.fixed1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.fixed1]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 588;
            this.DefaultHeight = 526;
            this.btn_close.HasDefault = true;
            this.Show();
            this.btn_close.Clicked += new System.EventHandler(this.OnBtnCloseClicked);
            this.btn_help.Clicked += new System.EventHandler(this.OnBtnHelpClicked);
        }
    }
}
