// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.UI {
    
    
    public partial class SettingsWindow {
        
        private Gtk.Action ManagePluginsAction;
        
        private Gtk.Action GeneralPreferencesAction;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Toolbar toolbar1;
        
        private Gtk.Notebook notebook3;
        
        private Gtk.HPaned hpaned2;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.TreeView all_plugins_treeview;
        
        private Gtk.VPaned vpaned1;
        
        private Gtk.ScrolledWindow scrolledwindow4;
        
        private Gtk.TreeView plugin_treeview;
        
        private Gtk.Label manage_plugins_lbl;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Button ok_btn;
        
        private Gtk.Button help_btn;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.UI.SettingsWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.ManagePluginsAction = new Gtk.Action("ManagePluginsAction", Mono.Unix.Catalog.GetString("_Manage Plugins"), null, "gtk-execute");
            this.ManagePluginsAction.ShortLabel = Mono.Unix.Catalog.GetString("_Manage Plugins");
            w2.Add(this.ManagePluginsAction, null);
            this.GeneralPreferencesAction = new Gtk.Action("GeneralPreferencesAction", Mono.Unix.Catalog.GetString("General _Preferences"), null, "gtk-preferences");
            this.GeneralPreferencesAction.ShortLabel = Mono.Unix.Catalog.GetString("General _Preferences");
            w2.Add(this.GeneralPreferencesAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.WidthRequest = 650;
            this.HeightRequest = 500;
            this.Name = "Do.UI.SettingsWindow";
            this.Title = Mono.Unix.Catalog.GetString("Do Settings");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-preferences", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.Resizable = false;
            this.AllowGrow = false;
            this.DefaultWidth = 650;
            this.DefaultHeight = 500;
            // Container child Do.UI.SettingsWindow.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='ManagePluginsAction'/><toolitem action='GeneralPreferencesAction'/></toolbar></ui>");
            this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
            this.toolbar1.Name = "toolbar1";
            this.toolbar1.ShowArrow = false;
            this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(2));
            this.toolbar1.IconSize = ((Gtk.IconSize)(5));
            this.vbox3.Add(this.toolbar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.toolbar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.notebook3 = new Gtk.Notebook();
            this.notebook3.CanFocus = true;
            this.notebook3.Name = "notebook3";
            this.notebook3.CurrentPage = 0;
            this.notebook3.ShowBorder = false;
            this.notebook3.ShowTabs = false;
            // Container child notebook3.Gtk.Notebook+NotebookChild
            this.hpaned2 = new Gtk.HPaned();
            this.hpaned2.CanFocus = true;
            this.hpaned2.Name = "hpaned2";
            this.hpaned2.Position = 201;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow2.Gtk.Container+ContainerChild
            Gtk.Viewport w4 = new Gtk.Viewport();
            w4.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.all_plugins_treeview = new Gtk.TreeView();
            this.all_plugins_treeview.CanFocus = true;
            this.all_plugins_treeview.Name = "all_plugins_treeview";
            this.all_plugins_treeview.HeadersClickable = true;
            w4.Add(this.all_plugins_treeview);
            this.scrolledwindow2.Add(w4);
            this.hpaned2.Add(this.scrolledwindow2);
            Gtk.Paned.PanedChild w7 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.scrolledwindow2]));
            w7.Resize = false;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.vpaned1 = new Gtk.VPaned();
            this.vpaned1.CanFocus = true;
            this.vpaned1.Name = "vpaned1";
            this.vpaned1.Position = 84;
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.scrolledwindow4 = new Gtk.ScrolledWindow();
            this.scrolledwindow4.CanFocus = true;
            this.scrolledwindow4.Name = "scrolledwindow4";
            this.scrolledwindow4.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow4.Gtk.Container+ContainerChild
            Gtk.Viewport w8 = new Gtk.Viewport();
            w8.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport1.Gtk.Container+ContainerChild
            this.plugin_treeview = new Gtk.TreeView();
            this.plugin_treeview.CanFocus = true;
            this.plugin_treeview.Name = "plugin_treeview";
            this.plugin_treeview.HeadersClickable = true;
            w8.Add(this.plugin_treeview);
            this.scrolledwindow4.Add(w8);
            this.vpaned1.Add(this.scrolledwindow4);
            Gtk.Paned.PanedChild w11 = ((Gtk.Paned.PanedChild)(this.vpaned1[this.scrolledwindow4]));
            w11.Resize = false;
            this.hpaned2.Add(this.vpaned1);
            this.notebook3.Add(this.hpaned2);
            // Notebook tab
            this.manage_plugins_lbl = new Gtk.Label();
            this.manage_plugins_lbl.Name = "manage_plugins_lbl";
            this.manage_plugins_lbl.LabelProp = Mono.Unix.Catalog.GetString("Manage Plugins");
            this.notebook3.SetTabLabel(this.hpaned2, this.manage_plugins_lbl);
            this.manage_plugins_lbl.ShowAll();
            this.vbox3.Add(this.notebook3);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox3[this.notebook3]));
            w14.Position = 1;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox3.Add(this.hseparator1);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.HeightRequest = 35;
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.ok_btn = new Gtk.Button();
            this.ok_btn.WidthRequest = 80;
            this.ok_btn.HeightRequest = 30;
            this.ok_btn.CanFocus = true;
            this.ok_btn.Name = "ok_btn";
            this.ok_btn.UseUnderline = true;
            // Container child ok_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w16 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w17 = new Gtk.HBox();
            w17.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w18 = new Gtk.Image();
            w18.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-ok", Gtk.IconSize.Menu, 16);
            w17.Add(w18);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w20 = new Gtk.Label();
            w20.LabelProp = Mono.Unix.Catalog.GetString("Ok");
            w20.UseUnderline = true;
            w17.Add(w20);
            w16.Add(w17);
            this.ok_btn.Add(w16);
            this.fixed1.Add(this.ok_btn);
            Gtk.Fixed.FixedChild w24 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.ok_btn]));
            w24.X = 564;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.help_btn = new Gtk.Button();
            this.help_btn.WidthRequest = 80;
            this.help_btn.HeightRequest = 30;
            this.help_btn.CanFocus = true;
            this.help_btn.Name = "help_btn";
            this.help_btn.UseUnderline = true;
            // Container child help_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w25 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            Gtk.HBox w26 = new Gtk.HBox();
            w26.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w27 = new Gtk.Image();
            w27.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-help", Gtk.IconSize.Menu, 16);
            w26.Add(w27);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w29 = new Gtk.Label();
            w29.LabelProp = Mono.Unix.Catalog.GetString("Help");
            w29.UseUnderline = true;
            w26.Add(w29);
            w25.Add(w26);
            this.help_btn.Add(w25);
            this.fixed1.Add(this.help_btn);
            Gtk.Fixed.FixedChild w33 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.help_btn]));
            w33.X = 5;
            this.vbox3.Add(this.fixed1);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox3[this.fixed1]));
            w34.Position = 3;
            w34.Expand = false;
            w34.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.ManagePluginsAction.Activated += new System.EventHandler(this.plugins_btnClicked);
            this.GeneralPreferencesAction.Activated += new System.EventHandler(this.preferences_btnClicked);
            this.ok_btn.Clicked += new System.EventHandler(this.ok_btnClicked);
            this.help_btn.Clicked += new System.EventHandler(this.help_btnClicked);
        }
    }
}
